/orbslam2/orbslam2_driver:
  ros__parameters:
    autostart: true
    camera_orientation_topic: /stanis/slam/zed_2i_driver/imu
    camera_topic_1: /stanis/slam/zed_2i_driver/left/image_rect_color
    camera_topic_2: /stanis/slam/zed_2i_driver/right/image_rect_color
    display: false
    frame_view: false
    link_namespace: ''
    mode: STEREO
    orb2_config_path: /home/neo/workspace/src/orbslam2_driver/config/ORB2_ZED2i_Stereo_VGA.yaml
    tracking_cpu: 2
    transport: raw
    use_sim_time: false
    verbose: false
    vocabulary_path: /home/neo/workspace/src/ORB-SLAM2/Vocabulary/orb_mur.fbow
