header_include_path: orbslam2_driver/orbslam2_driver.hpp
namespace: ORB_SLAM2Driver
node_class_name: ORB_SLAM2DriverNode

params:
  autostart:
    type: bool
    default_value: true
    description: "Activates system automatically at node startup."
    constraints: "Cannot be changed."
    read_only: true
    var_name: autostart_

  camera_orientation_topic:
    type: string
    default_value: "/camera/orientation"
    description: "Name of the camera orientation (IMU) topic."
    constraints: "Changes require system restart."
    read_only: false
    var_name: camera_orientation_topic_

  camera_topic_1:
    type: string
    default_value: "/camera/image_raw"
    description: "Name of the first camera topic."
    constraints: "Changes require system restart."
    read_only: false
    var_name: camera_topic_1_

  camera_topic_2:
    type: string
    default_value: "/camera/image_raw"
    description: "Name of the second camera topic."
    constraints: "Changes require system restart."
    read_only: false
    var_name: camera_topic_2_

  display:
    type: bool
    default_value: false
    description: "Activates the MapViewer GUI with Pangolin."
    constraints: "Changes require system restart, do not use on headless systems."
    read_only: false
    var_name: display_

  link_namespace:
    type: string
    default_value: ""
    description: "Link namespace, including the trailing slash."
    constraints: "Cannot be changed."
    read_only: true
    var_name: link_namespace_

  mode:
    type: string
    default_value: "STEREO"
    description: "ORB-SLAM2 mode, either MONOCULAR, STEREO, RGBD, or IRD."
    constraints: "Changes require system restart."
    read_only: false
    validator: validate_mode

  orb2_config_path:
    type: string
    default_value: ""
    description: "Path to the ORB-SLAM2 configuration file."
    constraints: "Changes require system restart."
    read_only: false
    var_name: orb2_config_path_

  transport:
    type: string
    default_value: "raw"
    description: "ROS image transport type, either raw or compressed."
    constraints: "Changes require system restart."
    read_only: false
    validator: validate_transport

  verbose:
    type: bool
    default_value: false
    description: "Activates verbose output."
    constraints: "Changes require system restart."
    read_only: false
    var_name: verbose_

  vocabulary_path:
    type: string
    default_value: ""
    description: "Path to the ORB vocabulary file."
    constraints: "Changes require system restart."
    read_only: false
    var_name: vocabulary_path_
