%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters for Left IR Camera (OpenCV)
# From camera intrinsics
# K matrix
Camera.fx: 379.895904541016
Camera.fy: 379.895904541016
Camera.cx: 317.829040527344
Camera.cy: 242.992126464844

# D matrix
Camera.k1: 0
Camera.k2: 0
Camera.p1: 0
Camera.p1: 0
Camera.k3: 0

# Computed from chessboard
# Camera.fx: 3.8239546117370509e+02
# Camera.fy: 3.8219648513972737e+02
# Camera.cx: 3.2027438449003421e+02
# Camera.cy: 2.3990883258792343e+02

# Camera.k1: 1.3224423549010711e-02
# Camera.k2: -1.5857661047632438e-02
# Camera.p1: -1.3443119021054313e-03
# Camera.p2: 1.9553483509142503e-03
# Camera.k3: 2.3106074488014841e-02

# Camera frames per second 
Camera.fps: 30.0

# Refer to: https://github.com/IntelRealSense/librealsense/issues/2580

# IR projector baseline times fx (approx.)
# Fx = 379.895904541016 (from get_instrinsics)
# b  = 50 / 1000 = 0.05 (from depth module baseline)
# bf = 379.895904541016 * 0.05
# Computed manually
# Camera.bf: 18.994795227
Camera.bf: 18.9481182098389

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times
# Points seen as close by the stereo/RGBD sensor are considered reliable and 
# inserted from just one frame. Far points require a match in two keyframes.
ThDepth: 5000.0
# ThDepth: 1.0e+09

# Depthmap values factor for rescaling
# DepthMapFactor = 1000, which is the conversion from millimeters to meters (Realsense provides depth in millimeters)
DepthMapFactor: 999.999938964844

# Modeling Realsense D435 Sensor Noise for Improved 3D Reconstruction and Tracking.
sensor_processor/type: structured_light
sensor_processor/cutoff_min_depth: 0.2
sensor_processor/cutoff_max_depth: 3.25
sensor_processor/normal_factor_a: 0.000611
sensor_processor/normal_factor_b: 0.003587
sensor_processor/normal_factor_c: 0.3515
sensor_processor/normal_factor_d: 0
sensor_processor/normal_factor_e: 1
sensor_processor/lateral_factor: 0.01576

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

ORBextractor.patchSize: 31

ORBextractor.halfPatchSize: 15

ORBextractor.edgeThreshold: 19

#--------------------------------------------------------------------------------------------
# Loop Closing Parameters
#--------------------------------------------------------------------------------------------
# For each loop candidate check consistency with previous loop candidates.
# Each candidate expands a covisibility group (keyframes connected to the loop 
# candidate in the covisibility graph). A group is consistent with a previous
# group if they share at least a keyframe. We must detect a consistent loop in
# several consecutive keyframes to accept it (the consecutive keyframes are given
# by the mnCovisibilityConsistencyTh).
LoopClosing.covisibilityConsistencyThreshold: 3

# If the map contains less than a minimum keyframes or less than these keyframes
# have passed from last loop detection, return false as no loop detected.
LoopClosing.minimumKeyFrames: 10

# NN Ratio for Sim3 ORB matcher
LoopClosing.sim3nnRatioOrbMatcher: 0.75

# Threshold to trigger RANSAC on Sim3
LoopClosing.ransacThresholdTrigger: 20

# Loop Closing RANSAC parameters
LoopClosing.ransacProbability: 0.99
LoopClosing.ransacMinimalInliers: 20
LoopClosing.ransacMaxIterations: 300

# Loop detection threshold (the loop is considered as detected if the matches are greater or
# equal to this threshold).
LoopClosing.detectionThreshold: 40

#--------------------------------------------------------------------------------------------
# Optimizer Parameters
#--------------------------------------------------------------------------------------------
# 2D Huber threshold.
Optimizer.2DHuberThreshold: 5.99

# 3D Huber threshold.
Optimizer.3DHuberThreshold: 7.815

# Initial Lambda for the Levenberg algorithm.
Optimizer.initialLambda: 1.0e-16

# Amount of covisible keyframes.
Optimizer.covisibleKeyframes: 100

# Number of optimization iterations for essential graph.
Optimizer.essentialGraphIterations: 20

# Number of optimization iterations for sim3.
Optimizer.sim3Iterations: 5

# Number of additional iterations if there are outliers.
Optimizer.additionalIterations: 10

# Number of additional iterations if there are no outliers.
Optimizer.additionalIterationsNoOutliers: 5

# Minimum number of inliers left before failing whole optimization.
Optimizer.minimumInliersBeforeFail: 10

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

#--------------------------------------------------------------------------------------------
# Map Parameters
#--------------------------------------------------------------------------------------------
Map.mapfile: map.bin
